services:
  frontend:
    image: frontend
    build: ./frontend
    ports:
      - "8080:8080"
  # pdfexport:
  #   image: pdfexport
  #   build: ./pdfexport
  # timemanagement:
  #   image: timemanagement
  #   build: ./timemanagement
  # usermanagement:
  #   image: usermanagement
  #   build: ./usermanagement
