version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgresDB
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      ## neu ##
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql