name: Deploy Dev

on:
  workflow_run:
    workflows: ["Build Dev"]
    types:
      - completed

env:
PROJECT_ID: vaulted-art-327315 
GAR_LOCATION: europe-west3
REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Cloud Run - Frontend
        id: deploy-frontend
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: frontendservice
          region: ${{ env.REGION }}
          image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/frontend:${{ github.sha }}"