name: Deploy Main

on:
  workflow_run:
    workflows: ["Build Main"]
    types:
      - completed

env:
    PROJECT_ID: vaulted-art-327315 
    GAR_LOCATION: europe-west3
    REGION: us-central1

jobs:
    deploy:
        runs-on: ubuntu-latest

        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            - name: Checkout
              uses: actions/checkout@v2
    
            - name: Google Auth
              id: auth
              uses: 'google-github-actions/auth@v2.0.1'
              with:
                project_id: '${{env.PROJECT_ID}}'
                token_format: 'access_token'
                workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
                service_account: '${{ secrets.SA_EMAIL }}'
        
            - name: Deploy to Cloud Run - Frontend
              id: deploy-frontend
              uses: google-github-actions/deploy-cloudrun@v2.0.0
              with:
                service: frontendservice
                region: ${{ env.REGION }}
                image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/worktimetraceregistry/frontend-image:${{ github.sha }}"

            - name: Deploy to Cloud Run - UserManagement
              id: deploy-usermanagement
              uses: google-github-actions/deploy-cloudrun@v2.0.0
              with:
                service: usermanagementservice
                region: ${{ env.REGION }}
                image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/worktimetraceregistry/usermanagement-image:${{ github.sha }}"

            - name: Deploy to Cloud Run - TimeManagement
              id: deploy-timemanagement
              uses: google-github-actions/deploy-cloudrun@v2.0.0
              with:
                service: timemanagementservice
                region: ${{ env.REGION }}
                image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/worktimetraceregistry/timemanagement-image:${{ github.sha }}"

            - name: Deploy to Cloud Run - PdfExport
              id: deploy-pdfexport
              uses: google-github-actions/deploy-cloudrun@v2.0.0
              with:
                service: pdfexportservice
                region: ${{ env.REGION }}
                image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/worktimetraceregistry/pdfexport-image:${{ github.sha }}"